project_name: terraform-provider-defguard

before:
  hooks:
    - go mod tidy

builds:
  - id: terraform-provider-defguard
    main: .
    binary: terraform-provider-defguard
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: archive
    builds:
      - terraform-provider-defguard
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"

signs:
  - artifacts: checksum
    cmd: gpg
    args:
      - --batch
      - --yes
      - --pinentry-mode
      - loopback
      - --passphrase
      - "{{ .Env.GPG_PASSPHRASE }}"
      - --output
      - "${signature}"
      - --detach-sign
      - "${artifact}"

release:
  github:
    owner: dburianov
    name: terraform-provider-defguard
  draft: false
  prerelease: "false"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
